// Avoxel284
// Andre Simulator cube (image generated by ai btw) ... easter egg

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AndreSimulator : MonoBehaviour {
	void Update() {
		transform.Rotate(8.0f * Time.deltaTime, 9.0f * Time.deltaTime, 8.0f * Time.deltaTime);
	}
}
